# Generated by Django 5.2.7 on 2026-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_1', '0002_alter_autor_id_alter_categoria_id_alter_libro_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_devolucion',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_prestamo',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='devuelto',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('EN_PRESTAMO', 'En préstamo'), ('DEVUELTO', 'Devuelto')], default='RESERVADO', max_length=12),
        ),
    ]
